---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      ansible.builtin.include_vars: vars/main.yml

    - name: Check telnet was installed
      ansible.builtin.stat:
        path: "/usr/local/bin/telnet"
      register: telnet_file

    - name: Check AppCleaner was installed
      ansible.builtin.stat:
        path: "/Applications/AppCleaner.app/Contents/MacOS/AppCleaner"
      register: cleaner_file

    - name: Check which taps are present
      ansible.builtin.command: brew tap
      changed_when: true
      register: taps

    - name: Assert telnet was Installed Correctly
      ansible.builtin.assert:
        that:
          - telnet_file.stat.exists
          - telnet_file.stat.executable
        msg: "The telnet binary must exist and be executable."

    - name: Assert App Cleaner was Installed Correctly
      ansible.builtin.assert:
        that:
          - cleaner_file.stat.exists
          - cleaner_file.stat.executable
        msg: "The App Cleaner binary must exist and be executable."

    - name: Assert Homebrew Taps were Installed Correctly
      ansible.builtin.assert:
        that:
          - brew_taps[0] in taps.stdout
        msg: "The configured homebrew taps be present."
