---
- name: Converge
  hosts: all
  connection: local
  tasks:

    - name: Load Scenario Variables
      include_vars: vars/main.yml

    - name: "Include homebrew-retry"
      include_role:
        name: "role-homebrew-retry"
