---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      ansible.builtin.include_vars: vars/main.yml

    - name: Check which taps are present
      ansible.builtin.command: brew tap
      changed_when: true
      register: taps

    - name: Assert Homebrew Taps were Installed Correctly
      ansible.builtin.assert:
        that:
          - brew_taps[0] in taps.stdout
        msg: "The configured homebrew taps be present."
