---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      include_vars: vars/main.yml

    - name: Check which taps are present
      command: brew tap
      changed_when: true
      register: taps

    - name: Assert Homebrew Taps were Installed Correctly
      assert:
        that:
          - brew_taps[0] in taps.stdout
        msg: "The configured homebrew taps be present."
